spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email
    username: coresmarttime
    password: dbtestpost
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

server:
  port: 8082

  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest

broker:
  queue:
    email:
      name: default.email
