spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: username
    password: password
    properties:
      mail:
        starttls:
          enable: true
        ssl:
          enable: false


server:
  port: 8082

broker:
  queue:
    email:
      name: users.v1.user-created
